/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'on-primary-container': '#eeefff',
        secondary: '#515f74',
        'primary-fixed': '#dbe1ff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#191c1e',
        'on-primary': '#ffffff',
        'surface-container': '#eaedff',
        'inverse-primary': '#b4c5ff',
        'tertiary-container': '#6b6e70',
        'on-secondary-fixed-variant': '#3a485b',
        'surface-container-high': '#e2e7ff',
        'surface-container-lowest': '#ffffff',
        background: '#faf8ff',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-tint': '#0053db',
        'primary-container': '#2563eb',
        'inverse-surface': '#283044',
        'on-tertiary-container': '#eff1f3',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed': '#00174b',
        'surface-bright': '#faf8ff',
        'on-secondary-container': '#57657a',
        'tertiary-fixed': '#e0e3e5',
        'on-tertiary-fixed-variant': '#444749',
        'surface-container-low': '#f2f3ff',
        tertiary: '#525657',
        'surface-variant': '#dae2fd',
        primary: '#004ac6',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-fixed-dim': '#b9c7df',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#003ea8',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        'secondary-container': '#d5e3fc',
        'on-background': '#131b2e',
        'on-secondary-fixed': '#0d1c2e',
        'surface-dim': '#d2d9f4',
        'on-surface-variant': '#434655',
        'secondary-fixed': '#d5e3fc',
        'surface-container-highest': '#dae2fd',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-surface': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        xs: '4px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        'margin-mobile': '16px',
        md: '16px',
        sm: '8px',
        gutter: '24px',
        'margin-desktop': '40px',
        base: '4px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-sm': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
};
